# Generated by Django 5.1.7 on 2025-03-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('about', models.TextField()),
                ('used_for', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('TR', 'Trees'), ('SH', 'Shrubs'), ('HB', 'Herbs'), ('FL', 'Flowers'), ('FR', 'Ferns'), ('GR', 'Grasses'), ('SU', 'Succulents and Cacti'), ('VI', 'Vines and Climbing Plants'), ('AQ', 'Aquatic Plants'), ('HP', 'Houseplants')], max_length=1024)),
                ('is_edible', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
